Enquiry module
converse-data-solutions/online_learning pull request #32
Opened 2024-03-13 08:18 UTC by aravindhan-converse

Enquire module created

2024-03-13 12:34 UTC, aravintsamy-converse approved these changes

2024-03-13 12:34 UTC, aravintsamy-converse commented on app/controllers/admin/enquires_controller.rb
> +    @enquire = Enquire.find(params[:id])
use find_by

2024-03-13 14:43 UTC, sivakumar-converse requested changes

2024-03-13 14:43 UTC, sivakumar-converse commented on app/models/enquire.rb
> +  def self.name_dropdown_filter(name)
use common method

2024-03-14 05:34 UTC, sivakumar-converse requested changes

2024-03-14 05:34 UTC, sivakumar-converse commented on app/models/enquire.rb
> +  def self.filter_enquires(params)
optimize this

2024-03-14 07:29 UTC, aravintsamy-converse approved these changes

2024-03-16 06:28 UTC, sivakumar-converse approved these changes

2024-03-16 06:30 UTC, merged