Trainer schedule
converse-data-solutions/online_learning pull request #37
Opened 2024-03-27 08:38 UTC by aravindhan-converse

Trainer & Schedule module

2024-03-30 06:36 UTC, aravintsamy-converse approved these changes

2024-03-30 06:36 UTC, aravintsamy-converse commented on app/controllers/admin/trainer_courses_controller.rb
> +  def render_invalid_trainer(format)
find the use or else remove it

2024-03-30 06:36 UTC, aravintsamy-converse commented on app/models/trainer_course.rb
> +  # validates :trainer_id, presence: true
remove it

2024-03-30 10:28 UTC, sivakumar-converse requested changes

2024-03-30 10:28 UTC, sivakumar-converse commented on app/controllers/admin/batches_controller.rb
> +      if @batch
alignment not correct

2024-03-30 10:28 UTC, sivakumar-converse commented on app/controllers/admin/batches_controller.rb
> +    render layout: false
use in class

2024-03-30 10:28 UTC, sivakumar-converse commented on app/controllers/admin/batches_controller.rb
> +        @batches = Batch.get_batches(params)
use around action

2024-03-30 10:28 UTC, sivakumar-converse commented on app/controllers/admin/batches_controller.rb
> +          @trainers = @course.trainers
use lint

2024-03-30 10:28 UTC, sivakumar-converse commented on app/controllers/admin/batches_controller.rb
> +      if @course
use lint

2024-03-30 10:29 UTC, aravindhan-converse commented on app/controllers/admin/trainer_courses_controller.rb
> +  def render_invalid_trainer(format)
removed

2024-03-30 10:29 UTC, aravindhan-converse commented on app/models/trainer_course.rb
> +  # validates :trainer_id, presence: true
removed

2024-03-30 10:37 UTC, aravindhan-converse commented on app/controllers/admin/batches_controller.rb
> +      if @batch
fixed

2024-03-30 10:37 UTC, aravindhan-converse commented on app/controllers/admin/batches_controller.rb
> +          @trainers = @course.trainers
fixed

2024-03-30 10:38 UTC, aravindhan-converse commented on app/controllers/admin/batches_controller.rb
> +      if @course
fixed

2024-04-05 17:17 UTC, sivakumar-converse approved these changes

2024-04-05 17:19 UTC, merged